### ISSUE TITLE
Cannot install through pip

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/html2kirby#2]
```
pip install html2kirby
Collecting html2kirby
  Using cached html2kirby-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8l/zn3jwvq974j53tmgdqv822dh0000gn/T/pip-build-qgsmfql1/html2kirby/setup.py", line 13, in <module>
        long_description=open(os.path.join(HERE, 'README.rst')).read(),
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/8l/zn3jwvq974j53tmgdqv822dh0000gn/T/pip-build-qgsmfql1/html2kirby/README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8l/zn3jwvq974j53tmgdqv822dh0000gn/T/pip-build-qgsmfql1/html2kirby/
```

Hint: I guess the MANIFEST.in file referencing the README.rst is missing.

**Comment by schtibe** [comment]
Thank you for your hint. I made a new sub-release 0.1-1 which should fix this issue. If you could test again that would be great!

**Comment by LeBenLeBen** [comment]
It works fine now 👌🏻
